language: python  
python: 
 - "3.6"  

install:  
 - pip install -r requirements.txt
 - pip install coveralls

 services:
  - postgresql

before_script:
  - psql -c 'create database test_store;' -U postgres


script: 
 - nosetests --exe --with-coverage --cover-package=app
 - coveralls

after_success:
 - coveralls